CREATE TABLE TB_CATEGORY(
        NAME VARCHAR2(10),
        USE_YN CHAR(1) DEFAULT 'Y'
        );
 
CREATE TABLE TB_CLASS_TYPE (
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10) );
    
ALTER TABLE TB_CATEGORY
ADD CONSTRAINT PK_CATEGORY_NAME PRIMARY KEY(NAME);

ALTER TABLE TB_CLASS_TYPE
MODIFY NAME NOT NULL;

ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR2(10);
ALTER TABLE TB_CLASS_TYPE
MODIFY NAME VARCHAR2(20);

ALTER TABLE TB_CATEGORY
MODIFY NAME VARCHAR2(20);

--6
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_NO;
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;

--7
ALTER TABLE TB_CATEGORY DROP CONSTRAINT PK_CATEGORY_NAME;
ALTER TABLE TB_CATEGORY ADD CONSTRAINT PK_CATEGORY_NAME PRIMARY KEY (CATEGORY_NAME);
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN CLASS_NO TO PK_CLASS_TYPE_NO;

--8
INSERT INTO TB_CATEGORY VALUES('공학' , 'Y');
INSERT INTO TB_CATEGORY VALUES('자연과학' , 'Y');
INSERT INTO TB_CATEGORY VALUES('의학' , 'Y');
INSERT INTO TB_CATEGORY VALUES('예체능' , 'Y');
INSERT INTO TB_CATEGORY VALUES('인문사회' , 'Y');

--9
ALTER TABLE TB_DEPARTMENT ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY (CATEGORY)
REFERENCES TB_CATEGORY(CATEGORY_NAME);








        
        
        
        