SELECT *
FROM EMPLOYEE;

SELECT JOB_NAME
FROM EMPLOYEE;

SELECT *
FROM DEPARTMENT;

SELECT EMP_NAME , EMAIL ,PHONE , HIRE_DATE
FROM EMPLOYEE;

SELECT EMP_NAME, SALARY, HIRE_DATE
FROM EMPLOYEE;


SELECT EMP_NAME, (SALARY*12), (SALARY+(SALARY*NVL(BONUS,0)))*12 AS 총수령액, (SALARY+(SALARY*NVL(BONUS,0)))*12 -(SALARY*12*0.03) AS 실수령액
FROM EMPLOYEE;


SELECT emp_name, salary, hire_date, phone 
FROM EMPLOYEE 
WHERE SAL_LEVEL = 'S1';


SELECT EMP_NAME, SALARY, (SALARY+(SALARY*NVL(BONUS,0)))*12 -(SALARY*12*0.03) AS 실수령액 , HIRE_DATE 
FROM EMPLOYEE
WHERE ROUND(SALARY*12-(SALARY*12*0.3),0) >=50000000;

SELECT *
FROM EMPLOYEE
WHERE SALARY >= 4000000 AND JOB_CODE = 'J2';

SELECT EMP_NAME, DEPT_CODE, HIRE_DATE
FROM EMPLOYEE
WHERE DEPT_CODE ='D9' OR DEPT_CODE ='D5' AND HIRE_DATE <= '02/01/01';


SELECT *
FROM EMPLOYEE
WHERE HIRE_DATE BETWEEN '90/01/01' AND '01/01/01';

SELECT *
FROM EMPLOYEE
WHERE EMP_NAME LIKE '__연';


SELECT EMP_NAME , PHONE
FROM EMPLOYEE
WHERE PHONE NOT LIKE '010%';

SELECT *
FROM EMPLOYEE
WHERE EMAIL LIKE '___!_%' ESCAPE'!' AND (DEPT_CODE = 'D9' OR DEPT_CODE = 'D6') AND HIRE_CODE BETWEEN '09/01/01' AND '00/12/01'
AND SALARY >= 2700000;


SELECT EMP_NAME , EMP_NO
FROM EMPLOYEE;



SELECT *
FROM EMPLOYEE
WHERE MOD(EMP_ID, 2) =1;


SELECT EMP_NAME , DEPT_CODE, SUBSTR(EMP_NO, 1,2) || '년' || SUBSTR(EMP_NO, 3,2) || '월' || SUBSTR(EMP_NO, 5,2) || '일'
--, EXTRACT(YER FROM SYSDATE) - EXTRACT(YER FROM TO_DATE(SUBSTR(EMP_NO , 1,2), 'RRRR')) 나이
    ,TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE), TO_DATE(SUBSTR(EMP_NO , 1,6), 'RRMMDD'))/ 12) -- 만나이 계산법
FROM EMPLOYEE;


SELECT COUNT(*), COUNT(  DECODE(   EXTRACT(YEAR FROM HIRE_DATE), 2001, 100, NULL)       ) AS "2001년"  
              ,  COUNT(  DECODE(   EXTRACT(YEAR FROM HIRE_DATE), 2002, 11, NULL)       ) AS "2002년" 
                 , COUNT(  DECODE(   EXTRACT(YEAR FROM HIRE_DATE), 2003, 1, NULL)       ) AS "2003년" 
            , COUNT(  DECODE(   EXTRACT(YEAR FROM HIRE_DATE), 2004, 1, NULL)       ) AS "2004년" 
FROM EMPLOYEE
